# fly.toml app configuration file generated for eidolon-vi-multiplayer-backend on 2025-07-10T13:07:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eidolon-vi-multiplayer-backend'
primary_region = 'ord'

[build]

[deploy]
  release_command = 'echo "No release command needed"'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[processes]
  app = 'npm start'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
